USE MASTER
GO

SELECT  
	D.TEXT SQLSTATEMENT, 
	A.SESSION_ID SPID, 
	ISNULL(B.STATUS,A.STATUS) STATUS, 
	A.LOGIN_NAME LOGIN, 
	A.HOST_NAME HOSTNAME, 
	C.BLKBY,  
	DB_NAME(B.DATABASE_ID) DBNAME, 
	B.COMMAND, 
	ROUND(B.PERCENT_COMPLETE,1) AS PERC_COMP,
	ISNULL(B.CPU_TIME, A.CPU_TIME) CPUTIME, 
	--A.READS,
	--A.WRITES,
	--B.READS,
	--B.WRITES,
	ISNULL((B.READS + B.WRITES),(A.READS + A.WRITES)) DISKIO,  
	A.LAST_REQUEST_START_TIME LASTBATCH, 
	A.PROGRAM_NAME
FROM    SYS.DM_EXEC_SESSIONS A    
LEFT JOIN    SYS.DM_EXEC_REQUESTS B    
	ON A.SESSION_ID = B.SESSION_ID   
LEFT JOIN (SELECT   A.REQUEST_SESSION_ID SPID,  B.BLOCKING_SESSION_ID BLKBY 
				FROM SYS.DM_TRAN_LOCKS AS A  
				INNER JOIN SYS.DM_OS_WAITING_TASKS AS B 
				ON A.LOCK_OWNER_ADDRESS = B.RESOURCE_ADDRESS ) C    
	ON A.SESSION_ID = C.SPID   
OUTER APPLY SYS.DM_EXEC_SQL_TEXT(SQL_HANDLE) D
WHERE D.TEXT IS NOT NULL
AND A.SESSION_ID <> (SELECT @@SPID)
--OR A.LOGIN_NAME = 'SA'

--DBCC OUTPUTBUFFER (74)

--SP_WHO2 ACTIVE

--KILL 55