--HOSWIZARD\PRESTO
SELECT  DISTINCT 
	C.SEQUENCE AS 'CR #'
	,S.CODE AS SUBJECT
	,UDS.ID AS 'STATUS'
	,A.CODE
	--,CASE WHEN C.ASSIGNED_TO IS NULL THEN NULL ELSE A.FNAME + ' ' +A.[NAME] END AS ASSIGNED_TO
	,G.CODE AS 'ASSIGNED_GROUP'
	--,CASE WHEN C.[SEQ_CLIENT] IS NULL THEN NULL ELSE CU.FNAME + ' ' + CU.[NAME] END AS CLIENT
	,C.[DATE_OPEN:] AS DATE_OPENED
	,C.[DUE_DATE:] AS DATE_DUE
	,C.[END_DATE] AS DATE_SCHED_ENDED
	,C.[ACT_END_DATE] AS DATE_ACTUAL_ENDED
	,CD.PDATE AS 'PASSED TO USER'
	,LEFT(CONVERT(NVARCHAR(1000),C.DESCRIPTION),1000) AS 'DESCRIPTION (TRUNCATED)'
	,LEFT(CONVERT(NVARCHAR(1000),C.REASON),1000) AS 'REASON (TRUNCATED)'
	,LEFT(CONVERT(NVARCHAR(1000),C.PF_EFF_NOT_CHNG),1000) AS 'EFFECT (TRUNCATED)'
	,CONVERT(NVARCHAR(2000),C.ROLL_OUT_PLAN) AS 'ROLL_OUT_PLAN'
	,CONVERT(NVARCHAR(1000),C.BACK_OUT_PLAN) AS 'BACK_OUT_PLAN'
	--,AT.[FILENAME]
FROM     MagicSDE.[_SMDBA_].[_CHANGE_] C WITH (READUNCOMMITTED)
JOIN MagicSDE.[_SMDBA_].[_GROUPS_] G WITH (READUNCOMMITTED)
	ON C.[_GROUP_] = G.SEQUENCE
	
JOIN MagicSDE.[_SMDBA_].[_CHANGEDET_] CD WITH (READUNCOMMITTED)
	ON C.SEQUENCE = CD.CHANGE
	
JOIN MagicSDE.[_SMDBA_].[_CMSTATUS_] UDS WITH (READUNCOMMITTED)
	ON C.[SEQ_CMSTATUS] = UDS.[SEQUENCE]
	
JOIN MagicSDE._SMDBA_._SUBJECTS_ S WITH (READUNCOMMITTED)
	ON C.[SUBJECT] = S.[SEQUENCE]
	
--JOIN MagicSDE._SMDBA_._PERSONNEL_ P  WITH (READUNCOMMITTED)
--	ON C.[INITIATOR] = P.SEQUENCE
	
JOIN MagicSDE._SMDBA_._PERSONNEL_ A  WITH (READUNCOMMITTED)
	ON C.[ASSIGNED_TO] = A.SEQUENCE
	
JOIN [MagicSDE].[_SMDBA_].[_CUSTOMER_] CU WITH (READUNCOMMITTED)
	ON ISNULL(C.[SEQ_CLIENT],2932) = CU.SEQUENCE
	
--LEFT JOIN [MagicSDE].[_SMDBA_].[_ATTACH_] AT WITH (READUNCOMMITTED)
--	ON C.SEQUENCE = AT.[SEQ_CHANGE]
	
WHERE CD.SEQUENCE = (SELECT MAX(SEQUENCE)
                    FROM   MagicSDE.[_SMDBA_].[_CHANGEDET_] WITH (READUNCOMMITTED)
                    WHERE  CHANGE = C.SEQUENCE
                           AND (ACTION = 56
                                 OR ACTION = 52))

--AND A.CODE IN('HAKIMA','MISTRYD','STEWARTD','DOLANJ')
AND G.[SEQUENCE] = 1014 --DBA_GROUP
AND C.[ACT_END_DATE] IS NULL
AND UDS.ID NOT IN ('CANCELLED','FAIL_BACKOUT','COMPLETED','REJECTED')
AND C.[DUE_DATE:] < GETDATE()
AND C.SEQUENCE > 77213
ORDER BY C.SEQUENCE DESC