--HOSWIZARD\PRESTO
SELECT  --TOP 20  
	C.SEQUENCE AS 'CR #',
	S.CODE AS SUBJECT,
	G.CODE AS 'GROUP',
	UDS.ID AS 'STATUS',
	CD.PDATE AS DATE_APPROVED,
		 LEFT(CONVERT(NVARCHAR(1000),C.DESCRIPTION),200) AS 'DESCRIPTION (TRUNCATED)'
FROM     MagicSDE.[_SMDBA_].[_CHANGE_] C WITH (READUNCOMMITTED)
JOIN MagicSDE.[_SMDBA_].[_GROUPS_] G WITH (READUNCOMMITTED)
	ON C.[_GROUP_] = G.SEQUENCE
JOIN MagicSDE.[_SMDBA_].[_CHANGEDET_] CD WITH (READUNCOMMITTED)
	ON C.SEQUENCE = CD.CHANGE
JOIN MagicSDE.[_SMDBA_].[_CMSTATUS_] UDS WITH (READUNCOMMITTED)
	ON C.SEQ_CMSTATUS = UDS.SEQUENCE
JOIN MagicSDE._SMDBA_._SUBJECTS_ S WITH (READUNCOMMITTED)
	ON C.SUBJECT = S.SEQUENCE
JOIN MagicSDE._SMDBA_._CMSTATUS_ ST WITH (READUNCOMMITTED)
	ON C.SEQ_CMSTATUS = ST.SEQUENCE
WHERE CD.SEQUENCE = (SELECT MAX(SEQUENCE)
                    FROM   MagicSDE.[_SMDBA_].[_CHANGEDET_] WITH (READUNCOMMITTED)
                    WHERE  CHANGE = C.SEQUENCE
                           AND (ACTION = 56
                                 OR ACTION = 52))
AND G.CODE = 'DBA_GROUP'
AND S.CODE = 'SCO'
--AND CONVERT(NVARCHAR(50),CD.[DESCRIPTION]) LIKE '%Change Status Changed To APPROVED%'
ORDER BY C.SEQUENCE DESC 