--HOSWIZARD\PRESTO
SELECT 
	T.SEQUENCE AS [INCIDENT #]
	,T.[DATE OPEN]
	,T.[SENT TO] AS [USER_CODE]
	,P.CODE AS [USER_NAME]
	,G.CODE AS [GROUP]
	,UDS.ID AS [STATUS]
	,T.[DATE OPEN] AS [DATE_OPEN]
	,TD.PDATE [PASSED TO USER]
	,T.[DUE_DATE:] AS [DATE_DUE]
	,T.[CLOSED ON] AS [DATE_CLOSED]
	,LEFT(CONVERT(NVARCHAR(1000),T.DESCRIPTION),1000) AS [DESCRIPTION (TRUNCATED)]
	,T.CONTACT_TYPE

FROM     [MagicSDE].[_SMDBA_].[_TELMASTE_] T WITH (READUNCOMMITTED)

JOIN [MagicSDE].[_SMDBA_].[_GROUPS_] G WITH (READUNCOMMITTED)
	ON T.[_GROUP_] = G.SEQUENCE
	
JOIN [MagicSDE].[_SMDBA_].[_TELDETAI_] TD WITH (READUNCOMMITTED)
	ON T.SEQUENCE = TD.[PROBLEM #]
	
JOIN [MagicSDE].[_SMDBA_].[_UDSTATUS_] UDS WITH (READUNCOMMITTED)
	ON T.[SEQ_UDSTATUS:] = UDS.SEQUENCE
	
JOIN [MagicSDE].[_SMDBA_].[_PERSONNEL_] P WITH (READUNCOMMITTED)
	ON T.[SENT TO] = P.SEQUENCE
	
JOIN [MagicSDE].[_SMDBA_].[_CUSTOMER_] CU WITH (READUNCOMMITTED)
	ON ISNULL(T.[CLIENT],2932) = CU.SEQUENCE	
WHERE TD.SEQUENCE = (SELECT MAX(SEQUENCE)
                            FROM   [MagicSDE].[_SMDBA_].[_TELDETAI_] WITH (READUNCOMMITTED)
                            WHERE  [PROBLEM #] = TD.[PROBLEM #]
                                   AND (ACTION = 8
                                         OR ACTION = 10))
         --AND T.STATUS = 'O'
         --AND G.CODE = 'DBA_GROUP'
         --AND P.CODE = 'EDENJ'
         --AND (CU.FNAME + ' ' + CU.[NAME]) = 'jon eden'
         --AND T.DESCRIPTION LIKE'%rssshadow\lands%'''
         AND T.[DATE OPEN] BETWEEN '2014-07-01 05:58:00.000' AND '2014-07-04 09:15:00.000' 
		 --AND T.[DATE OPEN] > '2014-07-03 05:58:00.000'
		 AND T.CONTACT_TYPE = 'Mail Listen'
ORDER BY T.SEQUENCE DESC
