--HOSWIZARD\PRESTO
--SELECT BY GROUP
SELECT 
	P.SEQUENCE
	,P.DATE_OPEN
	,P.DUE_DATE
	,P.LASTMODIFIED
	,P.DATE_CLOSED
	,P.LASTUSER
	,A.CODE
	,P.[_GROUP_]
	,LEFT(CONVERT(NVARCHAR(1000),P.DESCRIPTION),1000) AS [DESCRIPTION (TRUNCATED)]
	,P.PF_SYS_IMPACT
	,P.PF_IMP_SYS
	,P.RESOLUTION
	,P.NOTE
	,PF_ROOT_CAUSE
	,P.WORK_AROUND
	

FROM MagicSDE._SMDBA_._PROBMGMT_ P WITH (READUNCOMMITTED)
LEFT JOIN MagicSDE._SMDBA_._PERSONNEL_ A  WITH (READUNCOMMITTED)
	ON P.[ASSIGNEDTO] = A.SEQUENCE
WHERE P.[_GROUP_] = 1014 --DBA_GROUP
AND DATE_CLOSED IS NULL
--AND P.SEQUENCE IN (4046,4130,4165,4168,4169,4214,4226,4228,4265,4374)
ORDER BY SEQUENCE

--SELECT BY USER
SELECT A.*
	FROM MagicSDE._SMDBA_._PROBMGMT_ A WITH (READUNCOMMITTED)
	WHERE ASSIGNEDTO = 1077
	ORDER BY SEQUENCE desc

--SELECT * FROM [_SMDBA_].[_PERSONNEL_] ORDER BY 4