--HOSWIZARD\PRESTO
USE MAGICSDE
GO

SELECT   T.SEQUENCE AS 'INCIDENT #',
         --@MAGICUSER AS 'USER',
         T.[SEQ_PM:],
         G.CODE AS 'GROUP',
         UDS.ID AS 'STATUS',
         TD.PDATE 'PASSED TO USER', --COUNT(1),
         LEFT(CONVERT(NVARCHAR(100),T.DESCRIPTION),100) AS 'DESCRIPTION (TRUNCATED)'
		 --,REPLACE(REPLACE(CONVERT(VARCHAR(100), T.DESCRIPTION), CHAR(13), CHAR(32)), CHAR(10), CHAR(32)) AS 'COMMENTS'
FROM     [_SMDBA_].[_TELMASTE_] T WITH (READUNCOMMITTED)
JOIN	 [_SMDBA_].[_GROUPS_] G WITH (READUNCOMMITTED)
	ON	 T.[_GROUP_] = G.SEQUENCE
JOIN	 [_SMDBA_].[_TELDETAI_] TD WITH (READUNCOMMITTED)
	ON	 T.SEQUENCE = TD.[PROBLEM #]
JOIN	 [_SMDBA_].[_UDSTATUS_] UDS WITH (READUNCOMMITTED)
	ON	 T.[SEQ_UDSTATUS:] = UDS.SEQUENCE
WHERE   T.STATUS = 'C'
        AND T.[SEQ_PM:] = 3720
        AND TD.SEQUENCE = (SELECT MAX(SEQUENCE)
                            FROM   [_SMDBA_].[_TELDETAI_] WITH (READUNCOMMITTED)
                            WHERE  [PROBLEM #] = TD.[PROBLEM #]
                                   AND (ACTION = 8
                                         OR ACTION = 10))
ORDER BY 1 DESC      