--HOSWIZARD\PRESTO
SELECT  DISTINCT 
	C.SEQUENCE AS 'CR #'
	,S.CODE AS SUBJECT
	,UDS.ID AS 'STATUS'
	,CASE WHEN C.ASSIGNED_TO IS NULL THEN NULL ELSE A.FNAME + ' ' +A.[NAME] END AS ASSIGNED_TO
	,G.CODE AS 'ASSIGNED_GROUP'
	,CASE WHEN C.[SEQ_CLIENT] IS NULL THEN NULL ELSE CU.FNAME + ' ' + CU.[NAME] END AS CLIENT
	,C.[DATE_OPEN:] AS DATE_OPENED
	,C.[END_DATE] AS DATE_SCHED_ENDED
	,C.[ACT_END_DATE] AS DATE_ACTUAL_ENDED
	,CD.PDATE AS 'PASSED TO USER'
	,LEFT(CONVERT(NVARCHAR(1000),C.DESCRIPTION),1000) AS 'DESCRIPTION (TRUNCATED)'
	,LEFT(CONVERT(NVARCHAR(1000),C.REASON),1000) AS 'REASON (TRUNCATED)'
	,LEFT(CONVERT(NVARCHAR(1000),C.PF_EFF_NOT_CHNG),1000) AS 'EFFECT (TRUNCATED)'
	,CONVERT(NVARCHAR(2000),C.ROLL_OUT_PLAN) AS 'ROLL_OUT_PLAN'
	,CONVERT(NVARCHAR(1000),C.BACK_OUT_PLAN) AS 'BACK_OUT_PLAN'
	--,AT.[FILENAME]
FROM     MagicSDE.[_SMDBA_].[_CHANGE_] C WITH (READUNCOMMITTED)
JOIN MagicSDE.[_SMDBA_].[_GROUPS_] G WITH (READUNCOMMITTED)
	ON C.[_GROUP_] = G.SEQUENCE
	
JOIN MagicSDE.[_SMDBA_].[_CHANGEDET_] CD WITH (READUNCOMMITTED)
	ON C.SEQUENCE = CD.CHANGE
	
JOIN MagicSDE.[_SMDBA_].[_CMSTATUS_] UDS WITH (READUNCOMMITTED)
	ON C.[SEQ_CMSTATUS] = UDS.[SEQUENCE]
	
JOIN MagicSDE._SMDBA_._SUBJECTS_ S WITH (READUNCOMMITTED)
	ON C.[SUBJECT] = S.[SEQUENCE]
	
JOIN MagicSDE._SMDBA_._PERSONNEL_ P  WITH (READUNCOMMITTED)
	ON C.[INITIATOR] = P.SEQUENCE
	
JOIN MagicSDE._SMDBA_._PERSONNEL_ A  WITH (READUNCOMMITTED)
	ON ISNULL(C.[ASSIGNED_TO],1077) = A.SEQUENCE
	
JOIN [MagicSDE].[_SMDBA_].[_CUSTOMER_] CU WITH (READUNCOMMITTED)
	ON ISNULL(C.[SEQ_CLIENT],2932) = CU.SEQUENCE
	
LEFT JOIN [MagicSDE].[_SMDBA_].[_ATTACH_] AT WITH (READUNCOMMITTED)
	ON C.SEQUENCE = AT.[SEQ_CHANGE]
	
WHERE CD.SEQUENCE = (SELECT MAX(SEQUENCE)
                    FROM   MagicSDE.[_SMDBA_].[_CHANGEDET_] WITH (READUNCOMMITTED)
                    WHERE  CHANGE = C.SEQUENCE
                           AND (ACTION = 56
                                 OR ACTION = 52))
AND C.ASSIGNED_TO IS NOT NULL
--AND G.CODE = 'DBA_GROUP'
AND G.[SEQUENCE] = 1014 --DBA_GROUP
AND C.[ACT_END_DATE] IS NULL
AND UDS.ID NOT IN ('CANCELLED','FAIL_BACKOUT','COMPLETED','REJECTED')
AND C.[DATE_OPEN:] > '2014-01-01 00:00:00.000'
--AND S.CODE = 'SCO'
--AND C.DESCRIPTION like '% focus %'
--AND ROLL_OUT_PLAN LIKE '%CDR_Load_Control%'
--AND (CU.FNAME + ' ' + CU.[NAME]) = 'Jon Eden' --Client Information
--AND A.FNAME + ' ' +A.[NAME] = 'Jon Eden' --Assigned to
--AND P.FNAME + ' ' +P.[NAME]= 'Jon Eden'
--AND AT.[FILENAME] LIKE '%CDF_Load_Control%'
--AND C.SEQUENCE = 134352
--AND C.[DATE_OPEN:] BETWEEN '2014-05-01 00:00:00.000' AND '2014-05-22 10:20:40.847'
--AND C.[ACT_END_DATE] BETWEEN '2014-05-22 00:00:00.000' AND '2014-05-23 23:20:40.847'
ORDER BY C.[DATE_OPEN:] DESC