SELECT 
ISNULL((CASE WHEN GRO.CODE LIKE 'TECHNICAL_SERVICES%' THEN 'TECHNICAL_SERVICES' ELSE GRO.CODE END),'**Resolved By Not Specified**'),
SUM(CASE WHEN INC.PF_RESOLVE_TIME > INC.[DUE_DATE:] THEN 0 ELSE 1 END) AS 'SLA HIT',
COUNT(1) - SUM(CASE WHEN INC.PF_RESOLVE_TIME > INC.[DUE_DATE:] THEN 0 ELSE 1 END) AS 'SLA MISS',
COUNT(1) AS 'Total',
CONVERT(NUMERIC(8,2),ROUND((SUM(CASE WHEN INC.PF_RESOLVE_TIME > INC.[DUE_DATE:] THEN 0.00 ELSE 1.00 END) / COUNT(1)) * 100.00,2)) AS 'SLA Hit %age'
FROM [_SMDBA_].[_TELMASTE_] INC
INNER JOIN [_SMDBA_].[_SUBJECTS_] SUB
	ON INC.[SUBJECT] = SUB.SEQUENCE
LEFT JOIN [_SMDBA_].[_PERSONNEL_] STA
	ON INC.PF_RESOLVED = STA.SEQUENCE
LEFT JOIN [_SMDBA_].[_GROUPS_] GRO
	ON INC.PF_RESOLVED_GRP = GRO.SEQUENCE
WHERE [CLOSED ON] BETWEEN CONVERT(CHAR(4),YEAR(GETDATE()))+'-'+CONVERT(CHAR(2),MONTH(GETDATE()))+'-01 00:00:01' AND GETDATE()
AND SUB.CODE LIKE '%SR'
AND ISNULL(INC.CONTACT_TYPE,'') <> 'Event'
AND ISNULL(STA.NAME,'') <> 'Default'
--AND GRO.[SEQUENCE] = 1014
GROUP BY CASE WHEN GRO.CODE LIKE 'TECHNICAL_SERVICES%' THEN 'TECHNICAL_SERVICES' ELSE GRO.CODE END