
DECLARE @DBNAME VARCHAR(50)
DECLARE @NAME VARCHAR(50)
DECLARE @PERMISSION VARCHAR(15)
DECLARE @READONLY TINYINT	
DECLARE @ITEM_COUNTER INT
DECLARE @LOOP_COUNTER INT
DECLARE @ITEM_TABLE TABLE (ID INT IDENTITY(1,1),DBNAME VARCHAR(50))

SET @NAME = 'ho\spencerc'
SET @PERMISSION = 'db_datareader'

EXEC ('USE master; IF NOT EXISTS(SELECT name FROM sys.syslogins WHERE name LIKE ''%'+@NAME+''') BEGIN CREATE LOGIN ['+@NAME+'] FROM WINDOWS WITH DEFAULT_DATABASE=[master] END')
                            
INSERT INTO @ITEM_TABLE (DBNAME)
SELECT name FROM SYS.DATABASES WHERE database_id > 4 ORDER BY name

SET @LOOP_COUNTER = (SELECT COUNT(1) FROM @ITEM_TABLE)
SET @ITEM_COUNTER = 1

WHILE @LOOP_COUNTER > 0 AND @ITEM_COUNTER <= @LOOP_COUNTER
BEGIN

	SET @READONLY = 0

	IF EXISTS (SELECT name, is_read_only FROM SYS.databases WHERE name = @DBNAME AND is_read_only = 1 )
	BEGIN 
		SET @READONLY = 1
		EXEC('ALTER DATABASE '+ @DBNAME + ' SET READ_WRITE;')
	END	

	SELECT 
		@DBNAME = DBNAME
	FROM @ITEM_TABLE
	WHERE ID = @ITEM_COUNTER

	EXEC (N'USE ' + N'[' + @DBNAME + N'];IF NOT EXISTS(SELECT name FROM [sys].[sysusers] WHERE name = '''+@NAME+''') BEGIN CREATE USER ['+@NAME+'] FOR LOGIN ['+@NAME+'] EXEC sp_addrolemember N'''+@PERMISSION+''', N'''+@NAME+''' END')
	--EXEC (N'USE ' + N'[' + @DBNAME + N']; EXEC sp_addrolemember N'''+@PERMISSION+''', N'''+@NAME+''' ')

	IF @READONLY = 1
	BEGIN 
		EXEC('ALTER DATABASE '+ @DBNAME + ' SET READ_ONLY;')
	END 
			
	SET @ITEM_COUNTER = @ITEM_COUNTER + 1

END

