USE MASTER
GO

DECLARE @ALLROLES VARCHAR(3)
DECLARE	@USER VARCHAR(200)
DECLARE @ROLE VARCHAR(50)
DECLARE @DATABASE VARCHAR(40)
DECLARE @ALLMEMBERS VARCHAR(3)
DECLARE @ALLDATABASES VARCHAR(3)
DECLARE @TABLE TABLE (DBNAME VARCHAR(100))
DECLARE @TABLE2 TABLE (DBNAME VARCHAR(100), DBROLE VARCHAR(50),MEMBERNAME VARCHAR(200),MEMBERSID VARCHAR(500))
DECLARE @DB VARCHAR(40)

--THE @ALLROLES DETERMINES WHAT TO RETURN. IF YOU WANT TO RETURN ALL ROLES FOR A MEMBER SET AS YES.
--IF YOU WANT THE CODE TO RETURN A SPECIFIC ROLE FOR A MEMBER SET AS NO AND SET THE @ROLE TO THE 
--DESIRED ROLE.
--IF YOU WANT TO PROFILE A DATABASE RETURNING ALL MEMBERS AND ROLES SET @ALLMEMBERS TO YES OTHERWISE
--SET TO NO TO RETURN SPECIFIC MEMBER PROFILE

SET @ALLROLES = 'YES'
SET @ALLMEMBERS = 'YES'
SET @ALLDATABASES = 'YES'

--SET THE USER YOU ARE WANTING TO PROFILE
SET @USER = 'HO\BI'

--SET THE INDIVIDUAL ROLE TO PROFILE
SET @ROLE = 'DB_OWNER'

--SET THE DATABASE YOU WISH TO PROFILE
SET @DATABASE = 'DW_EDW'

IF (SELECT @ALLDATABASES) = 'YES'
BEGIN
	INSERT INTO @TABLE 
	SELECT [NAME] FROM SYS.DATABASES WHERE NAME NOT LIKE '%SNAPSHOT%'
END
ELSE
BEGIN
	INSERT INTO @TABLE 
	SELECT [NAME] FROM SYS.DATABASES WHERE NAME = @DATABASE
END

WHILE EXISTS (SELECT * FROM @TABLE)
BEGIN

	SELECT @DB = DBNAME FROM @TABLE

	IF (SELECT @ALLROLES) = 'YES'
	BEGIN 
		INSERT INTO @TABLE2 (DBROLE,MEMBERNAME,MEMBERSID)
		EXEC (N'USE ' + N'[' + @DB + N']; EXEC SP_HELPROLEMEMBER')
	END
	ELSE
	BEGIN
		INSERT INTO @TABLE2 (DBROLE,MEMBERNAME,MEMBERSID)
		EXEC (N'USE ' + N'[' + @DB + N']; EXEC SP_HELPROLEMEMBER '''+@ROLE+'''')
	END

	UPDATE @TABLE2
	SET DBNAME = @DB
	WHERE DBNAME IS NULL

	IF (SELECT @ALLMEMBERS) = 'NO'
	BEGIN 
		DELETE FROM @TABLE2 WHERE MEMBERNAME <> @USER
	END

	--IF (SELECT @ALLDATABASES) = 'NO'
	--BEGIN 
	--	DELETE FROM @TABLE2 WHERE DBNAME <> @DATABASE
	--END

	DELETE FROM @TABLE WHERE DBNAME = @DB

END

SELECT 
	@@SERVERNAME AS SERVER_NAME
	,DBNAME AS DATABASE_NAME
	,DBROLE AS DB_ROLE
	,MEMBERNAME AS LOGIN_NAME 
	--,MEMBERSID
FROM @TABLE2 
WHERE MEMBERNAME <> 'DBO'
ORDER BY 2

/****************************
SYSAdmins
****************************/ 
SELECT *
  FROM [msdb].[sys].[syslogins]
  WHERE [sysadmin] = 1
  
/****************************
Object Level Permissions
****************************/  
SELECT D.name as DATABASE_NAME
,O.name AS OBJECT_NAMES
,O.type_desc as OBJECT_TYPE
,O.object_id
,PR.name AS ROLE_NAME
,PE.grantee_principal_id
,PE.permission_name
,PE.state_desc
FROM sys.objects O
JOIN SYS.DATABASES D
	ON O.schema_id = D.database_id
JOIN sys.database_permissions PE
	ON O.object_id = PE.major_id
JOIN sys.database_principals PR
 ON PE.grantee_principal_id = PR.principal_id
WHERE D.name = 'DW_EDW'
AND PE.grantee_principal_id IN(18,12,8,21,16,26)
ORDER BY 2,5